Repository AY1920S1-CS2103T-T11-3/main, pull requests merged in 2019-10, with the labels that each got.

#76 AddEvent Implementation, Event Storage working, EventClass Semi Imple…
  .gitignore
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventEndDate.java
  src/main/java/seedu/address/model/event/EventStartDate.java
  src/main/java/seedu/address/model/event/EventVenue.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/resources/images/logo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/event/EventEndDateTest.java
  src/test/java/seedu/address/model/event/EventStartDateTest.java
Labels: priority.High, severity.Low, status.Ongoing, type.Chore

#82 Add Find_Ev and List_ev commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/ListEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindEventCommandParser.java
  src/main/java/seedu/address/model/event/EventNameContainsKeywordsPredicate.java
Labels: priority.High, status.Ongoing

#79 EditEvent Function/Feature Added - Test Case not done yet
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/EventRelatedCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/logo.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, status.Ongoing

#90 Update Event Management
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventDate.java
  src/main/java/seedu/address/model/event/EventDateTimeMap.java
  src/main/java/seedu/address/model/event/EventDayTime.java
  src/main/java/seedu/address/model/event/EventHoursNeeded.java
  src/main/java/seedu/address/model/event/EventId.java
  src/main/java/seedu/address/model/event/EventStartDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/resources/view/EventListCard.fxml
  src/test/java/seedu/address/model/event/EventDateTest.java
  src/test/java/seedu/address/model/event/EventDateTimeMapTest.java
  src/test/java/seedu/address/model/event/EventDayTimeTest.java
  src/test/java/seedu/address/model/event/EventEndDateTest.java
  src/test/java/seedu/address/model/event/EventHoursNeededTest.java
  src/test/java/seedu/address/model/event/EventIdTest.java
  src/test/java/seedu/address/model/event/EventManpowerNeededTest.java
  src/test/java/seedu/address/model/event/EventStartDateTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: priority.High

#109 Update Schedule Display -
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DisplayScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/processor/DistinctDatesProcessor.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/distinctDate/DistinctDate.java
  src/main/java/seedu/address/model/employee/Employee.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/ui/DateCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ScheduleBox.java
  src/main/resources/view/DateListCard.fxml
  src/main/resources/view/Schedule.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#134 EventDateTime Enhancements
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/allocate/AutoAllocateCommand.java
  src/main/java/seedu/address/logic/commands/allocate/DeallocateCommand.java
  src/main/java/seedu/address/logic/commands/allocate/ManualAllocateCommand.java
  src/main/java/seedu/address/logic/commands/event/AssignDateCommand.java
  src/main/java/seedu/address/logic/commands/event/ClearDateMappingCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteDateMappingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/event/ClearDateMappingCommandParser.java
  src/main/java/seedu/address/logic/parser/event/DeleteDateMappingCommandParser.java
  src/main/java/seedu/address/model/EventModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventDateTimeMap.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#136 EventDateTime: Enhancements and Bug Fixes
  src/main/java/seedu/address/logic/commands/event/AssignDateCommand.java
  src/main/java/seedu/address/logic/parser/event/AssignDateCommandParser.java
  src/main/java/seedu/address/model/event/EventDate.java
  src/main/java/seedu/address/model/event/EventDayTime.java
  src/test/java/seedu/address/model/event/EventDayTimeTest.java
Labels: priority.High
