Repository AY1920S1-CS2103T-T11-3/main, pull requests merged in 2019-11, with the labels that each got.

#235 EventDateTime Upgrades and Improvements
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/exceptions/OldDateException.java
  src/main/java/seedu/address/logic/commands/employee/ClearEmployeesCommand.java
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/event/AssignDateCommand.java
  src/main/java/seedu/address/logic/commands/event/ClearEventsCommand.java
  src/main/java/seedu/address/logic/commands/event/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/event/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/event/AssignDateCommandParser.java
  src/main/java/seedu/address/logic/parser/event/DeleteDateMappingCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/general/SetAppDateCommandParser.java
  src/main/java/seedu/address/logic/parser/schedule/DisplayScheduleBetweenParser.java
  src/main/java/seedu/address/logic/parser/schedule/DisplayScheduleForDateParser.java
  src/main/java/seedu/address/logic/processor/EmployeeEventProcessor.java
  src/main/java/seedu/address/model/employee/EmployeeJoinDate.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventDate.java
  src/main/java/seedu/address/model/event/EventDateTimeMap.java
  src/main/java/seedu/address/model/event/EventDayTime.java
  src/main/java/seedu/address/storage/JsonAdaptedEmployee.java
  src/test/java/seedu/address/logic/commands/AutoAllocateCommandTest.java
  src/test/java/seedu/address/logic/commands/ManualAllocateCommandTest.java
  src/test/java/seedu/address/logic/commands/employee/ClearEmployeesCommandTest.java
  src/test/java/seedu/address/logic/commands/employee/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/DisplayScheduleForDateParserTest.java
  src/test/java/seedu/address/logic/parser/EmployeeAddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#248 removed employeeJoinDate field, updated PPP
  docs/UserGuide.adoc
  docs/team/calvincxz.adoc
  docs/team/calvincxz.pdf
  src/main/java/seedu/address/logic/commands/allocate/AutoAllocateCommand.java
  src/main/java/seedu/address/logic/commands/allocate/DeallocateCommand.java
  src/main/java/seedu/address/logic/commands/allocate/ManualAllocateCommand.java
  src/main/java/seedu/address/logic/commands/employee/EditCommand.java
  src/main/java/seedu/address/logic/parser/employee/AddCommandParser.java
  src/main/java/seedu/address/logic/processor/EmployeeEventProcessor.java
  src/main/java/seedu/address/model/employee/Employee.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEmployee.java
  src/main/java/seedu/address/ui/FetchEventWindow.java
  src/test/java/seedu/address/storage/JsonAdaptedEmployeeTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: severity.Low

#249 Fixed UI sizing issue. Updated Testcases for Schedule Related command…
  src/main/java/seedu/address/logic/commands/event/AssignDateCommand.java
  src/main/java/seedu/address/logic/commands/event/ClearDateMappingCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteDateMappingCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/event/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/event/FetchEventCommand.java
  src/main/java/seedu/address/logic/commands/event/FindEventByTagCommand.java
  src/main/java/seedu/address/logic/commands/event/FindEventCommand.java
  src/main/java/seedu/address/model/distinctdate/DistinctDate.java
  src/main/java/seedu/address/model/event/EventContainsKeyYearMonthPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/schedule/DisplayScheduleBetweenCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/DisplayScheduleForDateCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/DisplayScheduleForYearMonthCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/GenerateScheduleCommandTest.java
  src/test/java/seedu/address/model/distinctdate/DistinctDateTest.java
  src/test/java/seedu/address/model/event/EventContainsKeyDatePredicateTest.java
  src/test/java/seedu/address/model/event/EventContainsKeyYearMonthPredicateTest.java
Labels: priority.High, severity.High
